---
title: "Acknowledgments"
execute:
  freeze: auto
---

Creating this validation platform has been a team effort, including representatives from SCTO affiliated units across Switzerland. There are many people that have contributed to its development, beyond those mentioned in the author lists of the individual documents, be it by testing, reviewing, or discussions. We would like to thank all of them for their contributions.

Alan Haynes, 
Alfonso Rojas,
André Moser,
Arnaud Künzi, 
Christina Huf,
Christine Otieno,
Christoph Combescure,
Constantin Sluka,
Cyril Jaksic,
David Krontaler,
Elio Carreras,
Erin West,
Hoda Mazaheri,
Julien Sauser,
Marie Roumet,
Mattia Branca,
Michael Coslovsky,
Mirelle Moser,
Monika Hebeisen,
Nicole Graf,
Odile Stalder,
Ramon Saccilotto,
Roland John,
Stefanie von Felten,
Synove Otterbech,
Ulrike Held, 
and many others.

Furthermore, this work builds off the ideas of various other groups, such as:

- [PHUSE's R Package Validation Framework](https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Data+Visualisation+%26+Open+Source+Technology/WP059.pdf)
- [The R Validation Hub](https://www.pharmar.org/)
- [A paper at PharmaSUG 2018 from Peter Schaefer and Debra Fontana](https://www.lexjansen.com/pharmasug/2018/SI/PharmaSUG-2018-SI13.pdf)

Finally, we thank you for using this platform and we hope it will be of great help to you in your work.
